name: Bug Report
description: Report a defect or regression in AlphaLab
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear description of the bug and observed behavior.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Exact commands/config used to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Python version, OS, command output snippets.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Tracebacks
      render: shell
